package AnnotatedSentence;

/**
 * Enumerated class for annotation layer types
 */
public enum ViewLayerType {
    PART_OF_SPEECH, INFLECTIONAL_GROUP, META_MORPHEME, META_MORPHEME_MOVED, TURKISH_WORD, PERSIAN_WORD, ENGLISH_WORD, WORD, SEMANTICS, NER, DEPENDENCY, PROPBANK, SHALLOW_PARSE, ENGLISH_PROPBANK, ENGLISH_SEMANTICS
}
