package AnnotatedSentence.DependencyError;

public enum DependencyErrorType {
    HEAD_EQUALS_ID, GO_LEFT_TO_RIGHT, NOT_EXPECTED_TO_HAVE_CHILDREN, SHOULDNT_BE_OF_POS, GAPS_IN_GOESWITH, PARENT_ORPHAN_SHOULD_BE_CONJ, PUNCTUATION_NOT_PROJECTIVE
}
